# -*- coding: utf-8 -*-
"""LSTM_AirPassengers_Forecast.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S7gNm-92lNzFmdja-SV7QugaSGaDq3xA
"""

# Import Libraries
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from keras.models import Sequential
from keras.layers import LSTM, Dense
from keras.metrics import MeanAbsoluteError
from sklearn.metrics import mean_squared_error

# Step 2: Load Dataset
df = pd.read_csv("/content/AirPassengers.csv")
df.columns = ['Month', 'Passengers']
df['Month'] = pd.to_datetime(df['Month'])
df.set_index('Month', inplace=True)
df.head()

# Normalize and Prepare Sequences
scaler = MinMaxScaler()
data_scaled = scaler.fit_transform(df[['Passengers']])

def create_sequences(data, time_step=12):
    X, y = [], []
    for i in range(len(data) - time_step):
        X.append(data[i:i+time_step])
        y.append(data[i+time_step])
    return np.array(X), np.array(y)

time_step = 12
X, y = create_sequences(data_scaled, time_step)
X = X.reshape((X.shape[0], X.shape[1], 1))

# Split into Training and Testing Sets
train_size = int(len(X) * 0.8)
X_train, X_test = X[:train_size], X[train_size:]
y_train, y_test = y[:train_size], y[train_size:]

# Build and Train LSTM Model
model = Sequential([
    LSTM(50, return_sequences=True, input_shape=(time_step, 1)),
    LSTM(50),
    Dense(1)
])
model.compile(optimizer='adam', loss='mean_squared_error', metrics=[MeanAbsoluteError()])
model.fit(X_train, y_train, epochs=50, batch_size=16)

# Predict and Plot Results
y_pred = model.predict(X_test)
y_test_inv = scaler.inverse_transform(y_test)
y_pred_inv = scaler.inverse_transform(y_pred)

plt.figure(figsize=(10,6))
plt.plot(y_test_inv, label='Actual')
plt.plot(y_pred_inv, label='Predicted')
plt.title('Air Passengers Forecasting using LSTM')
plt.xlabel('Time')
plt.ylabel('Passengers')
plt.legend()
plt.grid(True)
plt.show()